language: python
python: "2.7"
services:
 - mongodb
 - postgresql
install:
 - pip install pep8 --use-mirrors
 - pip install https://github.com/lamby/django-lint/archive/master.zip pylint --use-mirrors
 - pip install -r requirements.txt --use-mirrors
before_script:
 - psql -c 'create database test_nodewatcher;' -U postgres
 - pep8 nodewatcher
 - pylint nodewatcher
script:
 - ./manage.py test
