language: python
python: "2.7"
env: PYTHONPATH=. DJANGO_DATABASE_USER=postgres
services:
 - mongodb
 - postgresql
before_install:
 - cat /etc/apt/sources.list.d/*
 - sudo add-apt-repository -r -y ppa:ubuntugis/ppa
 - sudo apt-get update
 - sudo apt-get remove --purge postgresql-9.1-postgis-2.1 postgresql-9.1-postgis-scripts
 - sudo apt-get install binutils gdal-bin libproj-dev postgresql-9.1-postgis libgeoip1
install:
 - pip install pep8 --use-mirrors
 - pip install https://github.com/lamby/django-lint/archive/master.zip pylint --use-mirrors
 - pip install -r requirements.txt --use-mirrors
before_script:
 - find / -name postgis.sql || true
 - curl https://raw.github.com/django/django/1.5.1/docs/ref/contrib/gis/install/create_template_postgis-debian.sh | sh
 - createdb -T template_postgis nodewatcher
 - pep8 nodewatcher
 - pylint nodewatcher || true
script:
 - python -W error manage.py test
