language: python
python:
 - 2.6
 - 2.7
env: PYTHONPATH=. DJANGO_DATABASE_USER=postgres
services:
 - mongodb
 - postgresql
before_install:
 - sudo add-apt-repository -r -y ppa:ubuntugis/ppa
 - sudo apt-get update
 - sudo apt-get remove --purge postgresql-9.1-postgis-2.1 postgresql-9.1-postgis-scripts
 - sudo apt-get install postgresql-9.1-postgis libgeoip1
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
install:
 - pip install pep8 --use-mirrors
 - pip install https://github.com/lamby/django-lint/archive/master.zip pylint --use-mirrors
 - pip install -r requirements.txt --use-mirrors
before_script:
 - curl https://raw.githubusercontent.com/django/django/1.5.1/docs/ref/contrib/gis/install/create_template_postgis-debian.sh | sh
 - createdb -T template_postgis nodewatcher
 - pep8 nodewatcher
 - pylint nodewatcher || true
script:
 - python -W error manage.py test
