language: python
python:
 - 2.7
env: PYTHONPATH=. DB_1_ENV_PGSQL_SUPERUSER_USERNAME=postgres
services:
 - mongodb
 - postgresql
before_install:
 - sudo apt-get update
 - sudo apt-get install libgeoip1
 - sudo cat /code/packages.txt | DEBIAN_FRONTEND=noninteractive xargs apt-get --no-install-recommends -y --force-yes install
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
install:
 - pip install pep8 --use-mirrors
 - pip install https://github.com/lamby/django-lint/archive/master.zip pylint --use-mirrors
 - { cat requirements.txt | xargs -n 1 pip install; } || true
before_script:
 - createdb nodewatcher
 - psql -U postgres -c "create extension postgis" nodewatcher
 - pep8 nodewatcher
 - pylint nodewatcher || true
script:
 - python -W error manage.py test
