language: python
python: "2.7"
env:
 - PYTHONPATH=.
services:
 - mongodb
 - postgresql
install:
 - pip install pep8 --use-mirrors
 - pip install https://github.com/lamby/django-lint/archive/master.zip pylint --use-mirrors
 - pip install -r requirements.txt --use-mirrors
before_script:
 - psql -c 'create database test_nodewatcher;' -U postgres
 - curl https://docs.djangoproject.com/en/1.4/_downloads/create_template_postgis-debian.sh | sh
 - pep8 nodewatcher
 - pylint nodewatcher || true
script:
 - ./manage.py test
